/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package padrinhodobem;

import java.awt.Color;
import javax.swing.JOptionPane;
import padrinhodobem.utils.ValidadorCPF;
import padrinhodobem.utils.ValidadorEmail;

/**
 *
 * @author herbert
 */
public class UsuarioEditor extends javax.swing.JFrame {

    private boolean passwordStatus = false;
    
    private Usuario user;
    
    /**
     * Cria um novo usuario
     */
    public UsuarioEditor() {   
        initComponents();
        this.setTitle("Novo usuario");
        jLabel1.setText("Novo usuario");
        
        jTextField_id.setVisible(false);
    }
    
    /**
     * Edita um usuario existente
     */
    public UsuarioEditor(Usuario user) {
        this.user = user;
        initComponents();
        this.setTitle("Editar usuario");

        
        this.jTextField_id.setText(Integer.toString(user.getId()));

        
        this.jTextField_nome.setText(user.getNome());
        this.jTextField_email.setText(user.getEmail());
        this.jTextField_cpf.setText(user.getCpf());
        
        this.jPasswordField1.setText("*********");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_id = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 100));
        jTextField_nome = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 100));
        jTextField_cpf = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 100));
        jTextField_email = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 100));
        jPanelPassword = new javax.swing.JPanel();
        jPanelPassProgress = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jProgressBar1 = new javax.swing.JProgressBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButton1 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        jPanel2 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButtonSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 500));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jTextField_id.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField_id.setText("001");
        jTextField_id.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        jTextField_id.setEnabled(false);
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_id);
        jPanel1.add(filler4);

        jTextField_nome.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField_nome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        jTextField_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_nome);
        jPanel1.add(filler3);

        jTextField_cpf.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField_cpf.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        jTextField_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cpfActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_cpf);
        jPanel1.add(filler5);

        jTextField_email.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField_email.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_email);
        jPanel1.add(filler2);

        jPanelPassword.setLayout(new javax.swing.BoxLayout(jPanelPassword, javax.swing.BoxLayout.LINE_AXIS));

        jPanelPassProgress.setLayout(new javax.swing.BoxLayout(jPanelPassProgress, javax.swing.BoxLayout.PAGE_AXIS));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        jPanelPassProgress.add(jPasswordField1);

        jProgressBar1.setForeground(new java.awt.Color(255, 102, 102));
        jProgressBar1.setValue(70);
        jProgressBar1.setBorderPainted(false);
        jPanelPassProgress.add(jProgressBar1);

        jPanelPassword.add(jPanelPassProgress);
        jPanelPassword.add(filler1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/padrinhodobem/eye.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelPassword.add(jButton1);

        jPanel1.add(jPanelPassword);
        jPanel1.add(filler7);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);
        jPanel2.add(filler6);

        jButtonSave.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.background"));
        jButtonSave.setText("Salvar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSave);

        jPanel1.add(jPanel2);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuario");
        jLabel1.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        jProgressBar1.setValue(jPasswordField1.getPassword().length);
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        passwordStatus = !passwordStatus;

        
        jPasswordField1.setEchoChar((passwordStatus)? (char)0 : '*');
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    private void jTextField_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nomeActionPerformed

    private void jTextField_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cpfActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        String novaSenha = String.copyValueOf(this.jPasswordField1.getPassword());
        String novoCpf = jTextField_cpf.getText();
        String novoNome = jTextField_nome.getText();
        String novoEmail = jTextField_email.getText();
        
        
        // ToDo: Validar o CPF, Email e Senha
        if(! ValidadorCPF.validarCPF(novoCpf)){
            JOptionPane.showMessageDialog(null,"CPF Invalido, verifique e tente novamente!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!ValidadorEmail.validarEmail(novoEmail)){
            JOptionPane.showMessageDialog(null,"e-mail Invalido, verifique e tente novamente!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(novaSenha.length() < 5) {
            JOptionPane.showMessageDialog(null,"Senha Invalida, tente uma senha mais segura !", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Cria ou altera o usuario
        if(this.user == null) {
            this.user = new Usuario(novoEmail, novoCpf, novoNome, novaSenha);
        }else{
            this.user.setCpf(novoCpf);
            this.user.setEmail(novoEmail);
            this.user.setNome(novoNome);
            
            //Verifica se a senha foi alterada
            if(novaSenha != "*********"){
                this.user.setSenha(novaSenha);
            }
        }
 
        UsuarioDao db =  new UsuarioDao();       
        db.save(this.user);
        
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        jProgressBar1.setValue(jPasswordField1.getPassword().length * 11);
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPassProgress;
    private javax.swing.JPanel jPanelPassword;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField_cpf;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_nome;
    // End of variables declaration//GEN-END:variables
}
