/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package padrinhodobem.view;

/**
 *
 * @author herbert
 */
public class AdminDashboard extends javax.swing.JFrame {
    

    /**
     * Creates new form DashboardUsuario
     * 
     * 
     */
    public AdminDashboard() {
        initComponents();
        this.setTitle("Usuários");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        usuarioCrud1 = new padrinhodobem.view.usuario.UserDashboardView();
        criancaDashboardView1 = new padrinhodobem.view.crianca.CriancaDashboardView();
        necessidadeDashboardView1 = new padrinhodobem.view.necessidade.NecessidadeDashboardView();
        apadrinhamentoAdminDashboardView1 = new padrinhodobem.view.apadrinhamento.ApadrinhamentoAdminDashboardView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.addTab("Usuários", usuarioCrud1);
        jTabbedPane1.addTab("Criança", criancaDashboardView1);
        jTabbedPane1.addTab("Necessidade", necessidadeDashboardView1);
        jTabbedPane1.addTab("Apadrinhamentos", apadrinhamentoAdminDashboardView1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Usuários");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private padrinhodobem.view.apadrinhamento.ApadrinhamentoAdminDashboardView apadrinhamentoAdminDashboardView1;
    private padrinhodobem.view.crianca.CriancaDashboardView criancaDashboardView1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private padrinhodobem.view.necessidade.NecessidadeDashboardView necessidadeDashboardView1;
    private padrinhodobem.view.usuario.UserDashboardView usuarioCrud1;
    // End of variables declaration//GEN-END:variables
}
