package padrinhodobem.view;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import padrinhodobem.Dao.CriancaDao;
import padrinhodobem.entity.Crianca;
import padrinhodobem.entity.Usuario;
import padrinhodobem.view.crianca.CriancaCard;
import padrinhodobem.view.crianca.CriancaDashboardView;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mundo
 */
public class PadrinhoDashboard extends javax.swing.JFrame {
    private Usuario usuarioLogado;
    
    /**
     * Creates new form PadrinhoDashboardView
     */
    
    public PadrinhoDashboard(Usuario usuario) {  
        this.usuarioLogado = usuario;
        
        initComponents();
        
        var criancaDao = new CriancaDao();
        
        try {
           var criancaList = criancaDao.getAll();
           int nCrianca = criancaList.size();
           
           int cols = nCrianca >= 3 ? 3 : nCrianca;
           int rows = Math.ceilDiv(nCrianca, 3);
           
            jPanel2.setLayout(new java.awt.GridLayout(rows, cols, 10, 10));
            
            for (int i = 0; i < criancaList.size(); i++) {
                Crianca crianca = criancaList.get(i);
                
                var card = new CriancaCard(crianca, usuario);
                jPanel2.add(card);
            }
           
        } catch (Exception ex) {
            Logger.getLogger(CriancaDashboardView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    
     
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        apadrinhamentoDashboardView1 = new padrinhodobem.view.apadrinhamento.ApadrinhamentoDashboardView(this.usuarioLogado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setMaximumSize(new java.awt.Dimension(930, 420));
        jPanel2.setMinimumSize(new java.awt.Dimension(930, 420));
        jPanel2.setPreferredSize(new java.awt.Dimension(930, 420));
        jTabbedPane1.addTab("Apadrinhar ", jPanel2);

        apadrinhamentoDashboardView1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apadrinhamentoDashboardView1FocusGained(evt);
            }
        });
        apadrinhamentoDashboardView1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apadrinhamentoDashboardView1MouseClicked(evt);
            }
        });
        apadrinhamentoDashboardView1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                apadrinhamentoDashboardView1PropertyChange(evt);
            }
        });
        jTabbedPane1.addTab("Meus apadrinhamentos", apadrinhamentoDashboardView1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apadrinhamentoDashboardView1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apadrinhamentoDashboardView1FocusGained
        
    }//GEN-LAST:event_apadrinhamentoDashboardView1FocusGained

    private void apadrinhamentoDashboardView1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apadrinhamentoDashboardView1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_apadrinhamentoDashboardView1MouseClicked

    private void apadrinhamentoDashboardView1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_apadrinhamentoDashboardView1PropertyChange
       apadrinhamentoDashboardView1.updateTableData();
    }//GEN-LAST:event_apadrinhamentoDashboardView1PropertyChange

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
       var componente = jTabbedPane1.getSelectedComponent();
       if(componente == apadrinhamentoDashboardView1){
           apadrinhamentoDashboardView1.updateTableData();
       }
       return;
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private padrinhodobem.view.apadrinhamento.ApadrinhamentoDashboardView apadrinhamentoDashboardView1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
